import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const distDir = path.join(root, 'dist');
const deployDir = process.env.PAGES_DEPLOY_DIR || path.join(os.tmpdir(), `aimin-gh-pages-${Date.now()}`);
const userName = process.env.GIT_AUTHOR_NAME || 'github-actions-bot';
const userEmail = process.env.GIT_AUTHOR_EMAIL || 'github-actions-bot@users.noreply.github.com';
const preserveVisitorData = process.env.PRESERVE_VISITOR_DATA !== '0';
const visitorSyncFile = 'homepage-sync-data.js';
const visitorMapFile = 'visitor-map-data.js';

function run(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd || root,
    stdio: 'inherit',
    env: process.env
  });
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(' ')} failed with exit code ${result.status}`);
  }
}

function output(command, args, options = {}) {
  const result = spawnSync(command, args, {
    cwd: options.cwd || root,
    encoding: 'utf8',
    env: process.env
  });
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(' ')} failed with exit code ${result.status}`);
  }
  return result.stdout.trim();
}

function cleanup() {
  if (!fs.existsSync(deployDir)) return;
  spawnSync('git', ['worktree', 'remove', '--force', deployDir], { cwd: root, stdio: 'inherit' });
}

function parseHomepageSyncData(source) {
  const match = source.match(/window\.HOMEPAGE_SYNC_DATA\s*=\s*(\{[\s\S]*\});?\s*$/);
  if (!match) return null;
  try {
    return JSON.parse(match[1]);
  } catch {
    return null;
  }
}

function parseVisitorMapData(source) {
  const match = source.match(/window\.HOMEPAGE_VISITOR_WORLD_MAP\s*=\s*(\{[\s\S]*\});?\s*$/);
  if (!match) return null;
  try {
    return JSON.parse(match[1]);
  } catch {
    return null;
  }
}

function preserveVisitorSnapshot(previousSource, nextPath) {
  if (!previousSource || !fs.existsSync(nextPath)) return false;
  const previous = parseHomepageSyncData(previousSource);
  const next = parseHomepageSyncData(fs.readFileSync(nextPath, 'utf8'));
  if (!previous?.visitorSnapshot || !next) return false;

  next.visitorSnapshot = previous.visitorSnapshot;
  const banner = '/* Generated by scripts/sync-homepage-data.mjs. Visitor snapshot preserved during deployment. */';
  fs.writeFileSync(nextPath, `${banner}\nwindow.HOMEPAGE_SYNC_DATA = ${JSON.stringify(next, null, 2)};\n`);
  return true;
}

function preserveVisitorMapCounts(previousSource, nextPath) {
  if (!previousSource || !fs.existsSync(nextPath)) return false;
  const previous = parseVisitorMapData(previousSource);
  const next = parseVisitorMapData(fs.readFileSync(nextPath, 'utf8'));
  if (!previous?.activeCountries?.length || !next?.activeCountries?.length) return false;

  const nextByCode = new Map(next.activeCountries.map(country => [
    String(country.code || '').trim().toUpperCase(),
    country
  ]));

  next.activeCountries = previous.activeCountries.map((previousCountry, index) => {
    const code = String(previousCountry.code || '').trim().toUpperCase();
    const nextCountry = nextByCode.get(code);
    if (!nextCountry) return previousCountry;
    const { mergedMapRegions } = nextCountry;
    return {
      ...nextCountry,
      ...previousCountry,
      delay: previousCountry.delay ?? Number((index * 0.4).toFixed(1)),
      x: nextCountry.x,
      y: nextCountry.y,
      d: nextCountry.d,
      ...(mergedMapRegions ? { mergedMapRegions } : {})
    };
  });

  const banner = '/* Generated by scripts/generate-visitor-map-data.mjs. Visitor counts preserved during deployment. */';
  fs.writeFileSync(nextPath, `${banner}\nwindow.HOMEPAGE_VISITOR_WORLD_MAP = ${JSON.stringify(next)};\n`);
  return true;
}

if (!fs.existsSync(distDir)) {
  throw new Error('dist does not exist. Run npm run build before npm run deploy:pages.');
}

cleanup();
run('git', ['fetch', 'origin', 'gh-pages']);
run('git', ['worktree', 'add', deployDir, 'origin/gh-pages']);

try {
  const previousVisitorSyncPath = path.join(deployDir, visitorSyncFile);
  const previousVisitorMapPath = path.join(deployDir, visitorMapFile);
  const previousVisitorSync = preserveVisitorData && fs.existsSync(previousVisitorSyncPath)
    ? fs.readFileSync(previousVisitorSyncPath, 'utf8')
    : '';
  const previousVisitorMap = preserveVisitorData && fs.existsSync(previousVisitorMapPath)
    ? fs.readFileSync(previousVisitorMapPath, 'utf8')
    : '';

  // Git worktree checkout times can match a fresh build to the second. Compare
  // content as well so same-sized index files are never skipped as unchanged.
  run('rsync', ['-a', '--checksum', '--delete', '--exclude', '.git', `${distDir}/`, `${deployDir}/`]);

  if (preserveVisitorData) {
    const preservedSnapshot = preserveVisitorSnapshot(previousVisitorSync, path.join(deployDir, visitorSyncFile));
    const preservedMapCounts = preserveVisitorMapCounts(previousVisitorMap, path.join(deployDir, visitorMapFile));
    if (previousVisitorMap && !preservedMapCounts) {
      fs.writeFileSync(path.join(deployDir, visitorMapFile), previousVisitorMap);
    }
    if (preservedSnapshot || previousVisitorMap) {
      console.log('Preserved published visitor data. Set PRESERVE_VISITOR_DATA=0 to intentionally update it.');
    }
  }

  run('git', ['add', '-A'], { cwd: deployDir });

  const status = output('git', ['status', '--short'], { cwd: deployDir });
  if (!status) {
    console.log('No GitHub Pages changes to deploy.');
  } else {
    run('git', ['config', 'user.name', userName], { cwd: deployDir });
    run('git', ['config', 'user.email', userEmail], { cwd: deployDir });
    run('git', ['commit', '-m', 'Deploy synchronized homepage'], { cwd: deployDir });
    run('git', ['push', 'origin', 'HEAD:gh-pages'], { cwd: deployDir });
  }
} finally {
  cleanup();
}
